var quotes = [
	"All our dreams can come true, if we have the courage to pursue them.",
	"The secret of getting ahead is getting started.",
	"The best time to plant a tree was 20 years ago. The second best time is now.",
	"Only the paranoid survive.",
	"Do one thing every day that scares you",
	"Do what you feel in your heart to be right – for you’ll be criticized anyway.",
	"Happiness is not something ready made. It comes from your own actions.",
	"Impossible is I'm possible",
	"I can accept failure, everyone fails at something. But I can't accept not trying.",
	"Don’t Let Yesterday Take Up Too Much Of Today.",
	"All you need is actions",
	"One habit is only replaced by another habit.",
	"Do What You Can With All You Have, Wherever You Are.",
]